//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18063.
// 
#pragma warning disable 1591

namespace CongVaoApp.BxVinh.WebSrv {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseEntity))]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback XeGetAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback XeGetBienSoOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoaiXeGetAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback XeVaoBenInsertOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback MemberGetByUsernameOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = global::CongVaoApp.Properties.Settings.Default.CongVaoApp_BxVinh_WebSrv_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event XeGetAllCompletedEventHandler XeGetAllCompleted;
        
        /// <remarks/>
        public event XeGetBienSoCompletedEventHandler XeGetBienSoCompleted;
        
        /// <remarks/>
        public event LoaiXeGetAllCompletedEventHandler LoaiXeGetAllCompleted;
        
        /// <remarks/>
        public event XeVaoBenInsertCompletedEventHandler XeVaoBenInsertCompleted;
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event MemberGetByUsernameCompletedEventHandler MemberGetByUsernameCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XeGetAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Xe[] XeGetAll(string q, int Top) {
            object[] results = this.Invoke("XeGetAll", new object[] {
                        q,
                        Top});
            return ((Xe[])(results[0]));
        }
        
        /// <remarks/>
        public void XeGetAllAsync(string q, int Top) {
            this.XeGetAllAsync(q, Top, null);
        }
        
        /// <remarks/>
        public void XeGetAllAsync(string q, int Top, object userState) {
            if ((this.XeGetAllOperationCompleted == null)) {
                this.XeGetAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXeGetAllOperationCompleted);
            }
            this.InvokeAsync("XeGetAll", new object[] {
                        q,
                        Top}, this.XeGetAllOperationCompleted, userState);
        }
        
        private void OnXeGetAllOperationCompleted(object arg) {
            if ((this.XeGetAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XeGetAllCompleted(this, new XeGetAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XeGetBienSo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] XeGetBienSo() {
            object[] results = this.Invoke("XeGetBienSo", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void XeGetBienSoAsync() {
            this.XeGetBienSoAsync(null);
        }
        
        /// <remarks/>
        public void XeGetBienSoAsync(object userState) {
            if ((this.XeGetBienSoOperationCompleted == null)) {
                this.XeGetBienSoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXeGetBienSoOperationCompleted);
            }
            this.InvokeAsync("XeGetBienSo", new object[0], this.XeGetBienSoOperationCompleted, userState);
        }
        
        private void OnXeGetBienSoOperationCompleted(object arg) {
            if ((this.XeGetBienSoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XeGetBienSoCompleted(this, new XeGetBienSoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoaiXeGetAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LoaiXe[] LoaiXeGetAll() {
            object[] results = this.Invoke("LoaiXeGetAll", new object[0]);
            return ((LoaiXe[])(results[0]));
        }
        
        /// <remarks/>
        public void LoaiXeGetAllAsync() {
            this.LoaiXeGetAllAsync(null);
        }
        
        /// <remarks/>
        public void LoaiXeGetAllAsync(object userState) {
            if ((this.LoaiXeGetAllOperationCompleted == null)) {
                this.LoaiXeGetAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoaiXeGetAllOperationCompleted);
            }
            this.InvokeAsync("LoaiXeGetAll", new object[0], this.LoaiXeGetAllOperationCompleted, userState);
        }
        
        private void OnLoaiXeGetAllOperationCompleted(object arg) {
            if ((this.LoaiXeGetAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoaiXeGetAllCompleted(this, new LoaiXeGetAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XeVaoBenInsert", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long XeVaoBenInsert(string BienSo, int LoaiXe, string Ngay, string Username, int Cq_Id, bool VangLai, int giaoCa_Id) {
            object[] results = this.Invoke("XeVaoBenInsert", new object[] {
                        BienSo,
                        LoaiXe,
                        Ngay,
                        Username,
                        Cq_Id,
                        VangLai,
                        giaoCa_Id});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void XeVaoBenInsertAsync(string BienSo, int LoaiXe, string Ngay, string Username, int Cq_Id, bool VangLai, int giaoCa_Id) {
            this.XeVaoBenInsertAsync(BienSo, LoaiXe, Ngay, Username, Cq_Id, VangLai, giaoCa_Id, null);
        }
        
        /// <remarks/>
        public void XeVaoBenInsertAsync(string BienSo, int LoaiXe, string Ngay, string Username, int Cq_Id, bool VangLai, int giaoCa_Id, object userState) {
            if ((this.XeVaoBenInsertOperationCompleted == null)) {
                this.XeVaoBenInsertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXeVaoBenInsertOperationCompleted);
            }
            this.InvokeAsync("XeVaoBenInsert", new object[] {
                        BienSo,
                        LoaiXe,
                        Ngay,
                        Username,
                        Cq_Id,
                        VangLai,
                        giaoCa_Id}, this.XeVaoBenInsertOperationCompleted, userState);
        }
        
        private void OnXeVaoBenInsertOperationCompleted(object arg) {
            if ((this.XeVaoBenInsertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XeVaoBenInsertCompleted(this, new XeVaoBenInsertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Login(string username, string password) {
            object[] results = this.Invoke("Login", new object[] {
                        username,
                        password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string username, string password) {
            this.LoginAsync(username, password, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string username, string password, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        username,
                        password}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MemberGetByUsername", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Member MemberGetByUsername(string username) {
            object[] results = this.Invoke("MemberGetByUsername", new object[] {
                        username});
            return ((Member)(results[0]));
        }
        
        /// <remarks/>
        public void MemberGetByUsernameAsync(string username) {
            this.MemberGetByUsernameAsync(username, null);
        }
        
        /// <remarks/>
        public void MemberGetByUsernameAsync(string username, object userState) {
            if ((this.MemberGetByUsernameOperationCompleted == null)) {
                this.MemberGetByUsernameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMemberGetByUsernameOperationCompleted);
            }
            this.InvokeAsync("MemberGetByUsername", new object[] {
                        username}, this.MemberGetByUsernameOperationCompleted, userState);
        }
        
        private void OnMemberGetByUsernameOperationCompleted(object arg) {
            if ((this.MemberGetByUsernameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MemberGetByUsernameCompleted(this, new MemberGetByUsernameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Xe : BaseEntity {
        
        private long idField;
        
        private int tUYEN_IDField;
        
        private int dONVI_IDField;
        
        private int lOAIXE_IDField;
        
        private string bienSo_ChuField;
        
        private string bienSo_SoField;
        
        private System.DateTime luuHanhField;
        
        private System.DateTime tuyenCoDinhField;
        
        private short gheField;
        
        private short soKhachField;
        
        private double mucPhiField;
        
        private short namSanXuatField;
        
        private bool xeTaiField;
        
        private bool xeVangLaiField;
        
        private int hanhKhachHopDongField;
        
        private double giaVeField;
        
        private string anhField;
        
        private int cQ_IDField;
        
        private string gioXuatBenField;
        
        private bool chuaDangKyField;
        
        private System.Guid rowIdField;
        
        private System.DateTime ngayTaoField;
        
        private System.DateTime ngayCapNhatField;
        
        private string usernameField;
        
        private bool khoaField;
        
        private int bIEUDO_IDField;
        
        private System.DateTime baoHiemField;
        
        private string bienSoField;
        
        private Tuyen tuyenField;
        
        private string lOAIXE_TenField;
        
        private string dONVI_TenField;
        
        private string tUYEN_TenField;
        
        private string bIEUDO_TenField;
        
        private LoaiBieuDo loaiBieuDoField;
        
        private LaiXe laiXeField;
        
        /// <remarks/>
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int TUYEN_ID {
            get {
                return this.tUYEN_IDField;
            }
            set {
                this.tUYEN_IDField = value;
            }
        }
        
        /// <remarks/>
        public int DONVI_ID {
            get {
                return this.dONVI_IDField;
            }
            set {
                this.dONVI_IDField = value;
            }
        }
        
        /// <remarks/>
        public int LOAIXE_ID {
            get {
                return this.lOAIXE_IDField;
            }
            set {
                this.lOAIXE_IDField = value;
            }
        }
        
        /// <remarks/>
        public string BienSo_Chu {
            get {
                return this.bienSo_ChuField;
            }
            set {
                this.bienSo_ChuField = value;
            }
        }
        
        /// <remarks/>
        public string BienSo_So {
            get {
                return this.bienSo_SoField;
            }
            set {
                this.bienSo_SoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LuuHanh {
            get {
                return this.luuHanhField;
            }
            set {
                this.luuHanhField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TuyenCoDinh {
            get {
                return this.tuyenCoDinhField;
            }
            set {
                this.tuyenCoDinhField = value;
            }
        }
        
        /// <remarks/>
        public short Ghe {
            get {
                return this.gheField;
            }
            set {
                this.gheField = value;
            }
        }
        
        /// <remarks/>
        public short SoKhach {
            get {
                return this.soKhachField;
            }
            set {
                this.soKhachField = value;
            }
        }
        
        /// <remarks/>
        public double MucPhi {
            get {
                return this.mucPhiField;
            }
            set {
                this.mucPhiField = value;
            }
        }
        
        /// <remarks/>
        public short NamSanXuat {
            get {
                return this.namSanXuatField;
            }
            set {
                this.namSanXuatField = value;
            }
        }
        
        /// <remarks/>
        public bool XeTai {
            get {
                return this.xeTaiField;
            }
            set {
                this.xeTaiField = value;
            }
        }
        
        /// <remarks/>
        public bool XeVangLai {
            get {
                return this.xeVangLaiField;
            }
            set {
                this.xeVangLaiField = value;
            }
        }
        
        /// <remarks/>
        public int HanhKhachHopDong {
            get {
                return this.hanhKhachHopDongField;
            }
            set {
                this.hanhKhachHopDongField = value;
            }
        }
        
        /// <remarks/>
        public double GiaVe {
            get {
                return this.giaVeField;
            }
            set {
                this.giaVeField = value;
            }
        }
        
        /// <remarks/>
        public string Anh {
            get {
                return this.anhField;
            }
            set {
                this.anhField = value;
            }
        }
        
        /// <remarks/>
        public int CQ_ID {
            get {
                return this.cQ_IDField;
            }
            set {
                this.cQ_IDField = value;
            }
        }
        
        /// <remarks/>
        public string GioXuatBen {
            get {
                return this.gioXuatBenField;
            }
            set {
                this.gioXuatBenField = value;
            }
        }
        
        /// <remarks/>
        public bool ChuaDangKy {
            get {
                return this.chuaDangKyField;
            }
            set {
                this.chuaDangKyField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid RowId {
            get {
                return this.rowIdField;
            }
            set {
                this.rowIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NgayTao {
            get {
                return this.ngayTaoField;
            }
            set {
                this.ngayTaoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NgayCapNhat {
            get {
                return this.ngayCapNhatField;
            }
            set {
                this.ngayCapNhatField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public bool Khoa {
            get {
                return this.khoaField;
            }
            set {
                this.khoaField = value;
            }
        }
        
        /// <remarks/>
        public int BIEUDO_ID {
            get {
                return this.bIEUDO_IDField;
            }
            set {
                this.bIEUDO_IDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime BaoHiem {
            get {
                return this.baoHiemField;
            }
            set {
                this.baoHiemField = value;
            }
        }
        
        /// <remarks/>
        public string BienSo {
            get {
                return this.bienSoField;
            }
            set {
                this.bienSoField = value;
            }
        }
        
        /// <remarks/>
        public Tuyen Tuyen {
            get {
                return this.tuyenField;
            }
            set {
                this.tuyenField = value;
            }
        }
        
        /// <remarks/>
        public string LOAIXE_Ten {
            get {
                return this.lOAIXE_TenField;
            }
            set {
                this.lOAIXE_TenField = value;
            }
        }
        
        /// <remarks/>
        public string DONVI_Ten {
            get {
                return this.dONVI_TenField;
            }
            set {
                this.dONVI_TenField = value;
            }
        }
        
        /// <remarks/>
        public string TUYEN_Ten {
            get {
                return this.tUYEN_TenField;
            }
            set {
                this.tUYEN_TenField = value;
            }
        }
        
        /// <remarks/>
        public string BIEUDO_Ten {
            get {
                return this.bIEUDO_TenField;
            }
            set {
                this.bIEUDO_TenField = value;
            }
        }
        
        /// <remarks/>
        public LoaiBieuDo LoaiBieuDo {
            get {
                return this.loaiBieuDoField;
            }
            set {
                this.loaiBieuDoField = value;
            }
        }
        
        /// <remarks/>
        public LaiXe LaiXe {
            get {
                return this.laiXeField;
            }
            set {
                this.laiXeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Tuyen : BaseEntity {
        
        private int idField;
        
        private string tenField;
        
        private System.Guid dI_IDField;
        
        private System.Guid dEN_IDField;
        
        private bool noiTinhField;
        
        private System.Guid rowIdField;
        
        private System.DateTime ngayTaoField;
        
        private System.DateTime ngayCapNhatField;
        
        private string usernameField;
        
        private double hoaHongBanVeField;
        
        private double veSinhLuuBenField;
        
        private string dI_TenField;
        
        private string dEN_TenField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Ten {
            get {
                return this.tenField;
            }
            set {
                this.tenField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid DI_ID {
            get {
                return this.dI_IDField;
            }
            set {
                this.dI_IDField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid DEN_ID {
            get {
                return this.dEN_IDField;
            }
            set {
                this.dEN_IDField = value;
            }
        }
        
        /// <remarks/>
        public bool NoiTinh {
            get {
                return this.noiTinhField;
            }
            set {
                this.noiTinhField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid RowId {
            get {
                return this.rowIdField;
            }
            set {
                this.rowIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NgayTao {
            get {
                return this.ngayTaoField;
            }
            set {
                this.ngayTaoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NgayCapNhat {
            get {
                return this.ngayCapNhatField;
            }
            set {
                this.ngayCapNhatField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public double HoaHongBanVe {
            get {
                return this.hoaHongBanVeField;
            }
            set {
                this.hoaHongBanVeField = value;
            }
        }
        
        /// <remarks/>
        public double VeSinhLuuBen {
            get {
                return this.veSinhLuuBenField;
            }
            set {
                this.veSinhLuuBenField = value;
            }
        }
        
        /// <remarks/>
        public string DI_Ten {
            get {
                return this.dI_TenField;
            }
            set {
                this.dI_TenField = value;
            }
        }
        
        /// <remarks/>
        public string DEN_Ten {
            get {
                return this.dEN_TenField;
            }
            set {
                this.dEN_TenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GiaoCa))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Function))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Role))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CoQuan))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Member))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LoaiXe))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LaiXe))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LoaiBieuDo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Tuyen))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Xe))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class BaseEntity {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GiaoCa : BaseEntity {
        
        private int idField;
        
        private int cQ_IDField;
        
        private double doanhThuField;
        
        private int tongSoPhoiField;
        
        private string nguoiGiaoField;
        
        private string nguoiNhanField;
        
        private System.DateTime ngayTaoField;
        
        private System.DateTime ngayCapNhatField;
        
        private string usernameField;
        
        private System.Guid rowIdField;
        
        private bool duyetField;
        
        private bool ketThucField;
        
        private System.DateTime ngayKetThucField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int CQ_ID {
            get {
                return this.cQ_IDField;
            }
            set {
                this.cQ_IDField = value;
            }
        }
        
        /// <remarks/>
        public double DoanhThu {
            get {
                return this.doanhThuField;
            }
            set {
                this.doanhThuField = value;
            }
        }
        
        /// <remarks/>
        public int TongSoPhoi {
            get {
                return this.tongSoPhoiField;
            }
            set {
                this.tongSoPhoiField = value;
            }
        }
        
        /// <remarks/>
        public string NguoiGiao {
            get {
                return this.nguoiGiaoField;
            }
            set {
                this.nguoiGiaoField = value;
            }
        }
        
        /// <remarks/>
        public string NguoiNhan {
            get {
                return this.nguoiNhanField;
            }
            set {
                this.nguoiNhanField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NgayTao {
            get {
                return this.ngayTaoField;
            }
            set {
                this.ngayTaoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NgayCapNhat {
            get {
                return this.ngayCapNhatField;
            }
            set {
                this.ngayCapNhatField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid RowId {
            get {
                return this.rowIdField;
            }
            set {
                this.rowIdField = value;
            }
        }
        
        /// <remarks/>
        public bool Duyet {
            get {
                return this.duyetField;
            }
            set {
                this.duyetField = value;
            }
        }
        
        /// <remarks/>
        public bool KetThuc {
            get {
                return this.ketThucField;
            }
            set {
                this.ketThucField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NgayKetThuc {
            get {
                return this.ngayKetThucField;
            }
            set {
                this.ngayKetThucField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Function : BaseEntity {
        
        private int idField;
        
        private int pIDField;
        
        private int levelField;
        
        private short loaiField;
        
        private string tenField;
        
        private string anhField;
        
        private string moTaField;
        
        private string maField;
        
        private int thuTuField;
        
        private bool activeField;
        
        private bool giaTriMacDinhField;
        
        private string urlField;
        
        private System.Guid rowIdField;
        
        private string pIDListField;
        
        private bool publishField;
        
        private System.DateTime ngayTaoField;
        
        private System.DateTime ngayCapNhatField;
        
        private string nguoiTaoField;
        
        private bool deskField;
        
        private bool deskMacDinhField;
        
        private string docField;
        
        private Function _ParentField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int PID {
            get {
                return this.pIDField;
            }
            set {
                this.pIDField = value;
            }
        }
        
        /// <remarks/>
        public int Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        public short Loai {
            get {
                return this.loaiField;
            }
            set {
                this.loaiField = value;
            }
        }
        
        /// <remarks/>
        public string Ten {
            get {
                return this.tenField;
            }
            set {
                this.tenField = value;
            }
        }
        
        /// <remarks/>
        public string Anh {
            get {
                return this.anhField;
            }
            set {
                this.anhField = value;
            }
        }
        
        /// <remarks/>
        public string MoTa {
            get {
                return this.moTaField;
            }
            set {
                this.moTaField = value;
            }
        }
        
        /// <remarks/>
        public string Ma {
            get {
                return this.maField;
            }
            set {
                this.maField = value;
            }
        }
        
        /// <remarks/>
        public int ThuTu {
            get {
                return this.thuTuField;
            }
            set {
                this.thuTuField = value;
            }
        }
        
        /// <remarks/>
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        public bool GiaTriMacDinh {
            get {
                return this.giaTriMacDinhField;
            }
            set {
                this.giaTriMacDinhField = value;
            }
        }
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid RowId {
            get {
                return this.rowIdField;
            }
            set {
                this.rowIdField = value;
            }
        }
        
        /// <remarks/>
        public string PIDList {
            get {
                return this.pIDListField;
            }
            set {
                this.pIDListField = value;
            }
        }
        
        /// <remarks/>
        public bool Publish {
            get {
                return this.publishField;
            }
            set {
                this.publishField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NgayTao {
            get {
                return this.ngayTaoField;
            }
            set {
                this.ngayTaoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NgayCapNhat {
            get {
                return this.ngayCapNhatField;
            }
            set {
                this.ngayCapNhatField = value;
            }
        }
        
        /// <remarks/>
        public string NguoiTao {
            get {
                return this.nguoiTaoField;
            }
            set {
                this.nguoiTaoField = value;
            }
        }
        
        /// <remarks/>
        public bool Desk {
            get {
                return this.deskField;
            }
            set {
                this.deskField = value;
            }
        }
        
        /// <remarks/>
        public bool DeskMacDinh {
            get {
                return this.deskMacDinhField;
            }
            set {
                this.deskMacDinhField = value;
            }
        }
        
        /// <remarks/>
        public string Doc {
            get {
                return this.docField;
            }
            set {
                this.docField = value;
            }
        }
        
        /// <remarks/>
        public Function _Parent {
            get {
                return this._ParentField;
            }
            set {
                this._ParentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Role : BaseEntity {
        
        private int idField;
        
        private int cQ_IDField;
        
        private string tenField;
        
        private System.DateTime ngayTaoField;
        
        private System.DateTime ngayCapNhatField;
        
        private System.Guid rowIdField;
        
        private bool heThongField;
        
        private bool activeField;
        
        private string nguoiTaoField;
        
        private System.Guid loai_IDField;
        
        private string loai_TenField;
        
        private CoQuan _CoQuanField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int CQ_ID {
            get {
                return this.cQ_IDField;
            }
            set {
                this.cQ_IDField = value;
            }
        }
        
        /// <remarks/>
        public string Ten {
            get {
                return this.tenField;
            }
            set {
                this.tenField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NgayTao {
            get {
                return this.ngayTaoField;
            }
            set {
                this.ngayTaoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NgayCapNhat {
            get {
                return this.ngayCapNhatField;
            }
            set {
                this.ngayCapNhatField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid RowId {
            get {
                return this.rowIdField;
            }
            set {
                this.rowIdField = value;
            }
        }
        
        /// <remarks/>
        public bool HeThong {
            get {
                return this.heThongField;
            }
            set {
                this.heThongField = value;
            }
        }
        
        /// <remarks/>
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        public string NguoiTao {
            get {
                return this.nguoiTaoField;
            }
            set {
                this.nguoiTaoField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid Loai_ID {
            get {
                return this.loai_IDField;
            }
            set {
                this.loai_IDField = value;
            }
        }
        
        /// <remarks/>
        public string Loai_Ten {
            get {
                return this.loai_TenField;
            }
            set {
                this.loai_TenField = value;
            }
        }
        
        /// <remarks/>
        public CoQuan _CoQuan {
            get {
                return this._CoQuanField;
            }
            set {
                this._CoQuanField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CoQuan : BaseEntity {
        
        private int idField;
        
        private int pIDField;
        
        private int thuTuField;
        
        private int loaiField;
        
        private string tenField;
        
        private string maField;
        
        private string moTaField;
        
        private string pIDListField;
        
        private int levelField;
        
        private System.Guid rowIdField;
        
        private System.DateTime ngayTaoField;
        
        private System.DateTime ngayCapNhatField;
        
        private string nguoiTaoField;
        
        private bool activeField;
        
        private string nguoiCapNhatField;
        
        private CoQuan _ParentField;
        
        private int nSDField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int PID {
            get {
                return this.pIDField;
            }
            set {
                this.pIDField = value;
            }
        }
        
        /// <remarks/>
        public int ThuTu {
            get {
                return this.thuTuField;
            }
            set {
                this.thuTuField = value;
            }
        }
        
        /// <remarks/>
        public int Loai {
            get {
                return this.loaiField;
            }
            set {
                this.loaiField = value;
            }
        }
        
        /// <remarks/>
        public string Ten {
            get {
                return this.tenField;
            }
            set {
                this.tenField = value;
            }
        }
        
        /// <remarks/>
        public string Ma {
            get {
                return this.maField;
            }
            set {
                this.maField = value;
            }
        }
        
        /// <remarks/>
        public string MoTa {
            get {
                return this.moTaField;
            }
            set {
                this.moTaField = value;
            }
        }
        
        /// <remarks/>
        public string PIDList {
            get {
                return this.pIDListField;
            }
            set {
                this.pIDListField = value;
            }
        }
        
        /// <remarks/>
        public int Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid RowId {
            get {
                return this.rowIdField;
            }
            set {
                this.rowIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NgayTao {
            get {
                return this.ngayTaoField;
            }
            set {
                this.ngayTaoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NgayCapNhat {
            get {
                return this.ngayCapNhatField;
            }
            set {
                this.ngayCapNhatField = value;
            }
        }
        
        /// <remarks/>
        public string NguoiTao {
            get {
                return this.nguoiTaoField;
            }
            set {
                this.nguoiTaoField = value;
            }
        }
        
        /// <remarks/>
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        public string NguoiCapNhat {
            get {
                return this.nguoiCapNhatField;
            }
            set {
                this.nguoiCapNhatField = value;
            }
        }
        
        /// <remarks/>
        public CoQuan _Parent {
            get {
                return this._ParentField;
            }
            set {
                this._ParentField = value;
            }
        }
        
        /// <remarks/>
        public int NSD {
            get {
                return this.nSDField;
            }
            set {
                this.nSDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Member : BaseEntity {
        
        private int idField;
        
        private string hoField;
        
        private string tenField;
        
        private string motaField;
        
        private string anhField;
        
        private int cQ_IDField;
        
        private string usernameField;
        
        private string passwordField;
        
        private System.DateTime ngayTaoField;
        
        private System.DateTime ngayCapNhatField;
        
        private string emailField;
        
        private string mobileField;
        
        private string diaChiField;
        
        private bool activeField;
        
        private bool khoaField;
        
        private bool xacNhanField;
        
        private bool ngayXacNhanField;
        
        private bool chungThucField;
        
        private bool adminField;
        
        private System.Guid rowIdField;
        
        private string nguoiTaoField;
        
        private int loaiField;
        
        private string refUsernameField;
        
        private bool thuKyField;
        
        private int sLOnlineField;
        
        private string loai_TenField;
        
        private string phoneField;
        
        private int tinhField;
        
        private CoQuan _CoQuanField;
        
        private Role[] _RolesField;
        
        private Function[] _FunctionsField;
        
        private string gH_TenField;
        
        private int gH_IDField;
        
        private double luongField;
        
        private GiaoCa giaoCaField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Ho {
            get {
                return this.hoField;
            }
            set {
                this.hoField = value;
            }
        }
        
        /// <remarks/>
        public string Ten {
            get {
                return this.tenField;
            }
            set {
                this.tenField = value;
            }
        }
        
        /// <remarks/>
        public string Mota {
            get {
                return this.motaField;
            }
            set {
                this.motaField = value;
            }
        }
        
        /// <remarks/>
        public string Anh {
            get {
                return this.anhField;
            }
            set {
                this.anhField = value;
            }
        }
        
        /// <remarks/>
        public int CQ_ID {
            get {
                return this.cQ_IDField;
            }
            set {
                this.cQ_IDField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NgayTao {
            get {
                return this.ngayTaoField;
            }
            set {
                this.ngayTaoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NgayCapNhat {
            get {
                return this.ngayCapNhatField;
            }
            set {
                this.ngayCapNhatField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        public string DiaChi {
            get {
                return this.diaChiField;
            }
            set {
                this.diaChiField = value;
            }
        }
        
        /// <remarks/>
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        public bool Khoa {
            get {
                return this.khoaField;
            }
            set {
                this.khoaField = value;
            }
        }
        
        /// <remarks/>
        public bool XacNhan {
            get {
                return this.xacNhanField;
            }
            set {
                this.xacNhanField = value;
            }
        }
        
        /// <remarks/>
        public bool NgayXacNhan {
            get {
                return this.ngayXacNhanField;
            }
            set {
                this.ngayXacNhanField = value;
            }
        }
        
        /// <remarks/>
        public bool ChungThuc {
            get {
                return this.chungThucField;
            }
            set {
                this.chungThucField = value;
            }
        }
        
        /// <remarks/>
        public bool Admin {
            get {
                return this.adminField;
            }
            set {
                this.adminField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid RowId {
            get {
                return this.rowIdField;
            }
            set {
                this.rowIdField = value;
            }
        }
        
        /// <remarks/>
        public string NguoiTao {
            get {
                return this.nguoiTaoField;
            }
            set {
                this.nguoiTaoField = value;
            }
        }
        
        /// <remarks/>
        public int Loai {
            get {
                return this.loaiField;
            }
            set {
                this.loaiField = value;
            }
        }
        
        /// <remarks/>
        public string RefUsername {
            get {
                return this.refUsernameField;
            }
            set {
                this.refUsernameField = value;
            }
        }
        
        /// <remarks/>
        public bool ThuKy {
            get {
                return this.thuKyField;
            }
            set {
                this.thuKyField = value;
            }
        }
        
        /// <remarks/>
        public int SLOnline {
            get {
                return this.sLOnlineField;
            }
            set {
                this.sLOnlineField = value;
            }
        }
        
        /// <remarks/>
        public string Loai_Ten {
            get {
                return this.loai_TenField;
            }
            set {
                this.loai_TenField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public int Tinh {
            get {
                return this.tinhField;
            }
            set {
                this.tinhField = value;
            }
        }
        
        /// <remarks/>
        public CoQuan _CoQuan {
            get {
                return this._CoQuanField;
            }
            set {
                this._CoQuanField = value;
            }
        }
        
        /// <remarks/>
        public Role[] _Roles {
            get {
                return this._RolesField;
            }
            set {
                this._RolesField = value;
            }
        }
        
        /// <remarks/>
        public Function[] _Functions {
            get {
                return this._FunctionsField;
            }
            set {
                this._FunctionsField = value;
            }
        }
        
        /// <remarks/>
        public string GH_Ten {
            get {
                return this.gH_TenField;
            }
            set {
                this.gH_TenField = value;
            }
        }
        
        /// <remarks/>
        public int GH_ID {
            get {
                return this.gH_IDField;
            }
            set {
                this.gH_IDField = value;
            }
        }
        
        /// <remarks/>
        public double Luong {
            get {
                return this.luongField;
            }
            set {
                this.luongField = value;
            }
        }
        
        /// <remarks/>
        public GiaoCa GiaoCa {
            get {
                return this.giaoCaField;
            }
            set {
                this.giaoCaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LoaiXe : BaseEntity {
        
        private int idField;
        
        private string tenField;
        
        private int soGheField;
        
        private double mucThuField;
        
        private string bangLaiField;
        
        private System.Guid rowIdField;
        
        private string usernameField;
        
        private System.DateTime ngayTaoField;
        
        private System.DateTime ngayCapNhatField;
        
        private int thuTuField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Ten {
            get {
                return this.tenField;
            }
            set {
                this.tenField = value;
            }
        }
        
        /// <remarks/>
        public int SoGhe {
            get {
                return this.soGheField;
            }
            set {
                this.soGheField = value;
            }
        }
        
        /// <remarks/>
        public double MucThu {
            get {
                return this.mucThuField;
            }
            set {
                this.mucThuField = value;
            }
        }
        
        /// <remarks/>
        public string BangLai {
            get {
                return this.bangLaiField;
            }
            set {
                this.bangLaiField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid RowId {
            get {
                return this.rowIdField;
            }
            set {
                this.rowIdField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NgayTao {
            get {
                return this.ngayTaoField;
            }
            set {
                this.ngayTaoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NgayCapNhat {
            get {
                return this.ngayCapNhatField;
            }
            set {
                this.ngayCapNhatField = value;
            }
        }
        
        /// <remarks/>
        public int ThuTu {
            get {
                return this.thuTuField;
            }
            set {
                this.thuTuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LaiXe : BaseEntity {
        
        private long idField;
        
        private int dONVI_IDField;
        
        private int xE_IDField;
        
        private string tenField;
        
        private System.DateTime ngaySinhField;
        
        private string bangLaiField;
        
        private string loaiBangField;
        
        private System.DateTime ngayHetHanBangLaiField;
        
        private System.DateTime ngayHetHanGiayKhamSucKhoeField;
        
        private bool khoaField;
        
        private string anhField;
        
        private System.Guid rowIdField;
        
        private System.DateTime ngayTaoField;
        
        private System.DateTime ngayCapNhatField;
        
        private string usernameField;
        
        private string dONVI_TenField;
        
        private string xE_BienSoField;
        
        /// <remarks/>
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int DONVI_ID {
            get {
                return this.dONVI_IDField;
            }
            set {
                this.dONVI_IDField = value;
            }
        }
        
        /// <remarks/>
        public int XE_ID {
            get {
                return this.xE_IDField;
            }
            set {
                this.xE_IDField = value;
            }
        }
        
        /// <remarks/>
        public string Ten {
            get {
                return this.tenField;
            }
            set {
                this.tenField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NgaySinh {
            get {
                return this.ngaySinhField;
            }
            set {
                this.ngaySinhField = value;
            }
        }
        
        /// <remarks/>
        public string BangLai {
            get {
                return this.bangLaiField;
            }
            set {
                this.bangLaiField = value;
            }
        }
        
        /// <remarks/>
        public string LoaiBang {
            get {
                return this.loaiBangField;
            }
            set {
                this.loaiBangField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NgayHetHanBangLai {
            get {
                return this.ngayHetHanBangLaiField;
            }
            set {
                this.ngayHetHanBangLaiField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NgayHetHanGiayKhamSucKhoe {
            get {
                return this.ngayHetHanGiayKhamSucKhoeField;
            }
            set {
                this.ngayHetHanGiayKhamSucKhoeField = value;
            }
        }
        
        /// <remarks/>
        public bool Khoa {
            get {
                return this.khoaField;
            }
            set {
                this.khoaField = value;
            }
        }
        
        /// <remarks/>
        public string Anh {
            get {
                return this.anhField;
            }
            set {
                this.anhField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid RowId {
            get {
                return this.rowIdField;
            }
            set {
                this.rowIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NgayTao {
            get {
                return this.ngayTaoField;
            }
            set {
                this.ngayTaoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NgayCapNhat {
            get {
                return this.ngayCapNhatField;
            }
            set {
                this.ngayCapNhatField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string DONVI_Ten {
            get {
                return this.dONVI_TenField;
            }
            set {
                this.dONVI_TenField = value;
            }
        }
        
        /// <remarks/>
        public string XE_BienSo {
            get {
                return this.xE_BienSoField;
            }
            set {
                this.xE_BienSoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LoaiBieuDo : BaseEntity {
        
        private int idField;
        
        private string tenField;
        
        private short soTuyenKhoanField;
        
        private short cachNgayField;
        
        private bool khoanTuyenField;
        
        private bool haiTuyenTrenNgayField;
        
        private string usernameField;
        
        private System.DateTime ngayTaoField;
        
        private System.DateTime ngayCapNhatField;
        
        private System.Guid rowIdField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Ten {
            get {
                return this.tenField;
            }
            set {
                this.tenField = value;
            }
        }
        
        /// <remarks/>
        public short SoTuyenKhoan {
            get {
                return this.soTuyenKhoanField;
            }
            set {
                this.soTuyenKhoanField = value;
            }
        }
        
        /// <remarks/>
        public short CachNgay {
            get {
                return this.cachNgayField;
            }
            set {
                this.cachNgayField = value;
            }
        }
        
        /// <remarks/>
        public bool KhoanTuyen {
            get {
                return this.khoanTuyenField;
            }
            set {
                this.khoanTuyenField = value;
            }
        }
        
        /// <remarks/>
        public bool HaiTuyenTrenNgay {
            get {
                return this.haiTuyenTrenNgayField;
            }
            set {
                this.haiTuyenTrenNgayField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NgayTao {
            get {
                return this.ngayTaoField;
            }
            set {
                this.ngayTaoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NgayCapNhat {
            get {
                return this.ngayCapNhatField;
            }
            set {
                this.ngayCapNhatField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid RowId {
            get {
                return this.rowIdField;
            }
            set {
                this.rowIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void XeGetAllCompletedEventHandler(object sender, XeGetAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XeGetAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal XeGetAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Xe[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Xe[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void XeGetBienSoCompletedEventHandler(object sender, XeGetBienSoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XeGetBienSoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal XeGetBienSoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void LoaiXeGetAllCompletedEventHandler(object sender, LoaiXeGetAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoaiXeGetAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoaiXeGetAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LoaiXe[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LoaiXe[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void XeVaoBenInsertCompletedEventHandler(object sender, XeVaoBenInsertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XeVaoBenInsertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal XeVaoBenInsertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void MemberGetByUsernameCompletedEventHandler(object sender, MemberGetByUsernameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MemberGetByUsernameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MemberGetByUsernameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Member Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Member)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591